default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  password: Server01*
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: OneBitExchange_development

test:
  <<: *default
  database: OneBitExchange_test

production:
  <<: *default
  database: OneBitExchange_production
  username: OneBitExchange
  password: <%= ENV['ONEBITEXCHANGE_DATABASE_PASSWORD'] %>



  
  
  
  username: postgres
  password: Server01*